version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "23:30"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Moq
    versions:
    - 4.16.0
  - dependency-name: Microsoft.NET.Test.Sdk
    versions:
    - 16.8.3
  - dependency-name: Microsoft.CodeAnalysis.CSharp
    versions:
    - 3.8.0
